### ISSUE TITLE
KiCad

### ISSUE THREAD

**Issue by Ortogonale** [DurandA/reflow946#1]
Hi,  I can help with KiCad 5.x can you please share the physical dimension of the board with holes etc.. in CAD file format?

**Comment by DurandA** [comment]
Hi @Ortogonale and thank you for proposing your help.

> in CAD file format

Are you thinking about one format in particular? Would a drawing be good enough?

@eliasrm87 from Twitter also told me that he his working on a Kicad design.

**Comment by eliasrm87** [comment]
Hi @Ortogonale, I'm currently working on a KiCad 6.x project that I will be requesting to be merged soon.
