### ISSUE TITLE
BUG: SPI MISO and CLK pins interchanged

### ISSUE THREAD

**Issue by Quas7** [DurandA/reflow946#6]
MISO and CLK have been interchanged - no SPI connection to the MAX31855K this way.

[#define PIN_NUM_MISO 12](https://github.com/DurandA/reflow946-firmware/blob/6782341b24b91ee0388d14db7c9579f278806f31/main/max31855.c#L8)

Correct defines are:

```
#define PIN_NUM_MISO 14
#define PIN_NUM_CLK  12
```

**Comment by DurandA** [comment]
Hi @Quas7 👋 and thanks for the feedback.

This is a mistake that was introduced with the Kicad version (rev 1.1), see #7 for more details. I will make a new revision.

**Comment by DurandA** [comment]
Fixed in 5f84cfc61181377c1e6a4e7759f00b89bdffa89a. Thank you very much for raising this issue.
